workflows:
  my-workflow:
    scripts:
      - name: Build ipa for distribution
        script: xcode-project build-ipa \
                    --project"/moonlight-common/moonlight-common.xcodeproj" \
                    --scheme "${XCODE_SCHEME?}"
    artifacts:
      - build/ios/ipa/*.ipa
